script_key="oBpacYiqvVNEYrruawLMLMPNANOfZWpk";
setfpscap(10)

getgenv().gagConfig = {
    LOW_CPU = true,  -- Tralalero Tralala
    KICK_AFTER_GIFT_PET = true,  -- Kick after all GIFT_PET pets gifted
    AUTO_COLLECT = false,  -- Auto collect ALL fruit & pets
    GIFT_USERNAME = { 
"X9Zz0BAedT",
"jHMXDFWJPj",
"U3jNmGXTm7",
"0xtsmpW7Vm",
"9D51TVkBe4",
"3MBG7D5ArN",
"KT05yjxJJW",
"jBPFvBRiSY",
"mfJmklFpvF",
"ndQNxOPMZT",
"M6oSfmZgzU",
"K869Yrkztq",
"RXxAyXroG9",
"bY0IpMtAVr",
"1x2SccrhrK",
"QE64i6nTBp",
"ItAirPwGZ0",
"TVPJzvuUE6",
"2SKlgefXPJ",
"Ee6KTCi8ni",
"iNIun1oxyW",
"MOh2TBuvaX",
"nGTEeVBOFz",
"gkE2JjKTlZ",
"FYeBBMWMhx",
"rMVcGfF4mQ",
"IIFoO3Kd3Q",
"5W4DGGHUpX",
"12lo9b8uwm",
"hBsPzDktHi",
"5AXsOOJiRa",
"FoNq7yD4dP",
"ItsJaxon_bubble77",
"Thunderfernzippy",
"NexusGolden_Reaper26",
"NexusjaneSigmaCataly",
"MrsVera_hill",
"NexusJaxonEmerald30",
"ItsLiam_Catalyst29",
"NexusDoodleshady",
"TheRealElise_Rift23",
"Haz3lKnightSab3r2015",
"leozestSigma2008",
"CHARLOTTE_Xenon2006",
"SaddleSapphire",
"Th3R3alP3tt3r_Wizard",
"AidenToxicreef",
"MrsJohnNebulaOoze",
"KaraRadiance2019",
"N3xusSt3v3n_SHAD3",
"br00kTal0n",
"ITSONYX_Ghost57",
"ItsBenjamin_Rogue",
"Alphatwistjumpy2019",
"sethStarryKite34",
"MrsAddieBuilderSurge",
"NickBoltRadiance",
"Nexusdana_Comet2019",
"TheRealClaireDark201",
"ItsquinnHearthBuilde",
"TheRealEvan_VAPOR",
"MrsGraysonTempest",
"NexusEllieEcho2013",
"NexusPanda_Hyper2006",
"ericWillow42",
"EliFablehush",
"KayleeChaosdream",
"ItsAidenhush",
"NexusClaireFox2006",
"NexusEthanMagicZephy",
"Nexuslark_S0rcerer",
"GUSTY_Drift",
"MrsLunaB3ast",
"TheRealgustHawk2005",
"TheRealbethCookie201",
"TheRealbreezeQuackYT",
"ITSRIDER_glow",
"MrsbloomThunderbolt",
"ZacharyVapor2018",
"Gabriel_Shine68",
"MrsMasonGriffin15",
"N3xusJosiahWolf2006",
},  -- Username to gift
    GIFT_PET = { "Barn Owl" },  -- Pet name to gift
}

loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/85b3f7e4c867c468617e5c93fa3a818d.lua"))()
